//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsquareMasterTemplate.PrintPdfReferemce {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintPdfReferemce.IPrintPdf")]
    public interface IPrintPdf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPdf/PrintService", ReplyAction="http://tempuri.org/IPrintPdf/PrintServiceResponse")]
        void PrintService(byte[] filestreamarray);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrintPdfChannel : EsquareMasterTemplate.PrintPdfReferemce.IPrintPdf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintPdfClient : System.ServiceModel.ClientBase<EsquareMasterTemplate.PrintPdfReferemce.IPrintPdf>, EsquareMasterTemplate.PrintPdfReferemce.IPrintPdf {
        
        public PrintPdfClient() {
        }
        
        public PrintPdfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintPdfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintPdfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintPdfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PrintService(byte[] filestreamarray) {
            base.Channel.PrintService(filestreamarray);
        }
    }
}
